### ISSUE TITLE
rtu_ slave

### ISSUE THREAD

**Issue by micropyt** [sfera-labs/exo-sense-py-modbus#3]
Hi, I do some changes in the modbus.py, probably not implemented it correctly.
Can we communicate by email?
Where can I define Modbus slave address?

**Comment by giampiero7** [comment]
Hi,
please contact me from [here](https://www.sferalabs.cc/contacts/) and I'll reply to you by email.
You pass the addresses (you may have more that one) as a list to Serial.get_request(unit_addr_list, timeout).
